---
product-name: pivotal-container-service
network-properties:
  singleton_availability_zone:
    name: us-central1-a
  other_availability_zones:
  - name: us-central1-a
  - name: us-central1-b
  - name: us-central1-c
  network:
    name: pks
  service_network:
    name: pks-services
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((domain-crt))
      private_key_pem: ((domain-key))
  .properties.pks_api_hostname:
    value: api.pks.((subdomain-name)).((domain-name))
  .properties.plan1_selector.active.master_az_placement:
    value:
    - us-central1-a
    - us-central1-b
    - us-central1-c
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - us-central1-a
    - us-central1-b
    - us-central1-c
  .properties.plan1_selector.active.worker_instances:
    value: 1
  .properties.plan2_selector:
    value: Plan Inactive
  .properties.plan3_selector:
    value: Plan Inactive
  .properties.cloud_provider:
    value: GCP
  .properties.cloud_provider.gcp.project_id:
    value: ((gcp-project-id))
  .properties.cloud_provider.gcp.network:
    value: ((subdomain-name))-pcf-network
  .properties.cloud_provider.gcp.master_service_account:
    value: ((subdomain-name))-pks-master@((gcp-project-id)).iam.gserviceaccount.com
  .properties.cloud_provider.gcp.worker_service_account:
    value: ((subdomain-name))-pks-worker@((gcp-project-id)).iam.gserviceaccount.com
  .properties.vm_extensions:
    value:
    - public_ip
  .properties.telemetry_selector:
    value: disabled
errand-config:
  upgrade-all-service-instances:
    post-deploy-state: false
resource-config:
  pivotal-container-service:
    elb_names:
    - tcp:((subdomain-name))-pks-api
