---
product-name: harbor-container-registry
network-properties:
  network:
    name: pks-services
  other_availability_zones:
  - name: us-central1-a
  - name: us-central1-b
  - name: us-central1-c
  singleton_availability_zone:
    name: us-central1-a
product-properties:
  .properties.admin_password:
    value:
      secret: ((om-password))
  .properties.admin_password_for_smoketest:
    value:
      secret: ((om-password))
  .properties.auth_mode:
    value: db_auth
  .properties.clair_updater_interval:
    value: 0
  .properties.customize_container_network:
    value: default
  .properties.hostname:
    value: harbor.((subdomain-name)).((domain-name))
  .properties.no_proxy:
    value: 127.0.0.1,localhost,ui,registry
  .properties.registry_storage:
    value: filesystem
  .properties.server_cert_key:
    value:
      cert_pem: ((domain-crt))
      private_key_pem: ((domain-key))
  .properties.server_cert_ca:
    value: ((domain-ca))
  .properties.with_clair:
    value: true
  .properties.with_notary:
    value: true
errand-config:
  smoke-testing:
    post-deploy-state: when-changed
  uaa-deregistration:
    pre-delete-state: false
resource-config:
  harbor-app:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  smoke-testing:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
