---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: harbor-container-registry-*.pivotal
pivnet-product-slug: harbor-container-registry
product-version-regex: 1\.7\.(.*)
stemcell-iaas: google
